redirect = "testing one two"
[[redirects]]
from = "/blog"
to = "/projects"
[[redirects]]
from = ""
to = ""
[[redirects]]
from = ""
to = ""
[[redirects]]
from = ""
to = ""
[[redirects]]
from = ""
to = ""
