---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: tag_list
  name: categories
  label: Categories
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- name: client
  type: text
  config:
    required: false
  label: Client
- name: brief
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Brief
  description: 'An intro to the project brief '
- name: solution
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Solution
  description: A paragraph about our process & solution
pages:
- projects/panasonic-ces.md
- projects/rare-signals.md
