---
label: Home
hide_body: true
fields:
- type: text
  name: site_name
  label: Site name
- name: home_text
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Home text
- name: home_typer
  type: field_group
  config: {}
  fields:
  - name: type_text_list
    type: tag_list
    default: []
    label: type text list
  label: home typer
pages:
- data/theme.json
